### ISSUE TITLE
Update Readme to match other languages.

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/NavAbilitySDK.js#3]

**Comment by jim-hill-r** [comment]
@GearsAD 

I did not include an example in the js version. I think we should just link to our Demos repo or rename it NavAbilityExamples or something. I like the repo because I can run tests to ensure the example is always working and does not drift from reality.

I put this in my readme.
```
Example

An example repo will be released in the near future. If you need support today, please reach out to info@navability.io
```

**Comment by jim-hill-r** [comment]
@GearsAD If you are good with the two readmes, we can close.

**Comment by GearsAD** [comment]
Sounds good, closing.
