### ISSUE TITLE
Tag v0.1.0 Release

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/NavAbilitySDK.js#7]
Had some issues tagging. I thought the npm publish command would do it. Need to investigate and ensure tagging is done.

**Comment by GearsAD** [comment]
Done :rocket:

**Comment by jim-hill-r** [comment]
I don't see them. Is it a permissions thing? 
![image](https://user-images.githubusercontent.com/25872250/149824570-bb8ee093-ddc8-40cb-9456-1d056f2978be.png)

**Comment by GearsAD** [comment]
Oh, wait I misread this then. I thought it was the bucket issue for releasing it, my bad.

**Comment by GearsAD** [comment]
Looks like it doesn't by default, people are adding a step in to do it https://muffinman.io/blog/add-git-version-tag-after-publishing-to-npm/

**Comment by jim-hill-r** [comment]
Tagged manually. Figure out automation later.
